apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sb-operator
  template:
    metadata:
      labels:
        name: sb-operator
    spec:
      serviceAccountName: sb-operator
      containers:
        - name: sb-operator
          image: docker.io/dimssss/sb-test:0.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sb-operator"
