kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
spec:
  replicas: {{.Values.size}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.deployment.image}}
        ports:
          - containerPort: {{ .Values.deployment.containerPort }}