apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
spec:
  host: "{{ .Values.name }}.router.default.svc.cluster.local"
  to:
    kind: Service
    name: {{ .Values.name }}